{% set name = "large-image-source-tiff" %}
{% set version = "1.29.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9f99cf3ef0f2d2e3712ff17285b664a1e4d0119396d27f9c54e6fb4c6f27c834

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm
  run:
    - python >=3.8
    - large-image
    - libtiff
    - pylibtiff >=0.4.1
    - tifftools

test:
  imports:
    - large_image
    - large_image_source_tiff
  commands:
    - python -c "import large_image; large_image.tilesource.loadTileSources(); assert 'tiff' in large_image.tilesource.AvailableTileSources"

about:
  home: https://github.com/girder/large_image
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Python modules to work with large, multiresolution images - Tiff source
  description: |
    Python modules to work with large, multiresolution images - Tiff source. Large Image is developed and maintained by the Data & Analytics group at Kitware, Inc. for processing large geospatial and medical images.
  doc_url: https://girder.github.io/large_image/
  dev_url: https://github.com/girder/large_image

extra:
  recipe-maintainers:
    - banesullivan
    - manthey
    - giswqs
